apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/iamuseong-oss/catalog-service
  newTag: 97b20685b4df559d2260128a570211daee4beaea

resources:
- github.com/iamuseong-oss/catalog-service/k8s?ref=97b20685b4df559d2260128a570211daee4beaea
replicas:
- count: 2
  name: catalog-service
patches:
- path: patch-env.yml
- path: patch-resource.yml
- path: patch-volume.yml
