apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: catalog-config

images:
  - name: catalog-service
    newName: ghcr.io/iamuseong-oss/catalog-service
    newTag: latest

resources:
  - github.com/iamuseong-oss/catalog-service/k8s?ref=main
replicas:
  - name: catalog-service
    count: 2
patches:
  - path: patch-env.yml
  - path: patch-resource.yml
  - path: patch-volume.yml