apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/iamuseong-oss/order-service/k8s?ref=main 

configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: order-service

images:
- name: order-service
  newName: ghcr.io/iamuseong-oss/order-service
  newTag: latest

replicas:
- count: 2
  name: order-service
patches:
- path: patch-env.yml